language: android

sudo: required

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license.+'
    - 'android-sdk-license-.+'

script:
    - ./gradlew clean build -PdisablePreDex --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
